# =============================================
# Configs
# =============================================

title: 'plate'
src:
  root:       src
  fonts:      <%= site.src.root %>/fonts
  images:     <%= site.src.root %>/images
  scripts:    <%= site.src.root %>/javascripts
  styles:     <%= site.src.root %>/stylesheets
dest:
  root:       dist
  fonts:      <%= site.dest.root %>/fonts
  images:     <%= site.dest.root %>/images
  scripts:    <%= site.dest.root %>/javascripts
  styles:     <%= site.dest.root %>/stylesheets
